### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/t3SphinxThemeRtdDemoDocs#12]
**Alex**: Should we archive the repo t3SphinxThemeRtdDemoDocs and remove the published docs from repository [demo-t3SphinxThemeRtd](https://docs.typo3.org/m/typo3/demo-t3SphinxThemeRtd/main/en-us/)? We already have to more demo docs: ① [sphinx_typo3_theme_rendering_test](https://typo3-documentation.github.io/sphinx_typo3_theme_rendering_test) and ② [WritingReST/Reference.html](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference.html).

**Martin**: Yes, repo t3SphinxThemeRtd should be archived and its rendering be removed. Repo ① is required and used for testing the container dev version. Page ② is required as documentation for users.

**Comment by alexander-nitsche** [comment]
hi @susannemoog , hi @DanielSiepmann , how to best remove this repository from rendering and deploying to https://docs.typo3.org/m/typo3/demo-t3SphinxThemeRtd/main/en-us/ and remove that URL completely?

**Comment by susannemoog** [comment]
Done.
