### ISSUE TITLE
Modify the Typo3 Documentation head line and change color

### ISSUE THREAD

**Issue by all4innov** [TYPO3-Documentation/t3SphinxThemeRtdDemoDocs#2]
Hello, 
Please is it possible to cutomize this theme by changing the color and the head logo ?
The rest is really perfect and great job ;)

**Comment by marble** [comment]
Can you make a proposal? What changes would you like to see?

**Comment by all4innov** [comment]
Add two new parameters in **config.py** under the section # t3SphinxThemeRtd : 
**1) Logo**
```
# The path to use a customized Head logo picture
# By default it will use Typo3 Documentation Logo
head_logo = /path/to/logo.png
```

**2) Main color**
```
# The main color that will be used 
# By default the color is orange
main_color = #00008b
```

**Comment by sypets** [comment]
@medhioub What is your intention for doing this?

This theme is for the official TYPO3 documentation on docs.typo3.org. It conforms to the TYPO3 Style Guide (see [Web Styleguide](https://styleguide.typo3.org/patternlab/public/index.html)). So, while I agree, it might be nice to make some things configurable, I don't think logo and basic color schemes should be the ones, we will want to change here, but you may have a good reason for suggesting this.

**Comment by marble** [comment]
Obsolete - closed.
